version: "3.3"
services:

  pact-backend:
    build: ../../../hl7-diff-tool-backend
    image: pact-backend
    networks:
      - pact
    expose:
      - "8106"
    ports:
      - "8106:8106"
    container_name: pact
    volumes:
      - ../../data/pact/logs/:/var/log/pact/

  pact-reverse-proxy:
      build: ./reverse-proxy
      networks:
        - pact
      image: pact-reverse-proxy
      container_name: pact-reverse-proxy
      volumes:
          - ../../data/pact-reverse-proxy/logs/:/var/log/nginx/
          - ../../data/pact-reverse-proxy/html:/usr/share/nginx/html:ro
      ports:
          - "8085:8085"
      depends_on:
          - pact
      links:
          - pact:pact

networks:
  pact:
