version: "3.3"
services:

  pact-backend:
    build: ../../../hl7-diff-tool-backend
    image: pact-backend
    networks:
      - pact
    expose:
      - "8107"
    ports:
      - "8107:8107"
    container_name: pact-backend
    volumes:
      - ../../data/pact/logs/:/var/log/pact/

  pact-reverse-proxy:
      build:
        context: ../../../
        dockerfile: ./hl7-diff-tool-infra/containers/apps/reverse-proxy/Dockerfile
      networks:
        - pact
      image: pact-reverse-proxy
      container_name: pact-reverse-proxy
      volumes:
          - ../../data/pact-reverse-proxy/logs/:/var/log/nginx/
          - ../../data/pact-reverse-proxy/html:/usr/share/nginx/html:ro
      ports:
          - "8085:8085"
      depends_on:
          - pact-backend
      links:
          - pact-backend:pact-backend

networks:
  pact:
